export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES_END = 'FETCH_ARTICLES_END';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';

export const FETCH_ARTICLE_START = 'FETCH_ARTICLE_START';
export const FETCH_ARTICLE_END = 'FETCH_ARTICLE_END';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';

export const CREATE_ARTICLE_START = 'CREATE_ARTICLE_START';
export const CREATE_ARTICLE_END = 'CREATE_ARTICLE_END';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE';

export const EDIT_ARTICLE_START = 'EDIT_ARTICLE_START';
export const EDIT_ARTICLE_END = 'EDIT_ARTICLE_END';
export const EDIT_ARTICLE_SUCCESS = 'EDIT_ARTICLE_SUCCESS';
export const EDIT_ARTICLE_FAILURE = 'EDIT_ARTICLE_FAILURE';

export const DELETE_ARTICLE_START = 'DELETE_ARTICLE_START';
export const DELETE_ARTICLE_END = 'DELETE_ARTICLE_END';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE';

export const UNPUBLISH_ARTICLE_START = 'UNPUBLISH_ARTICLE_START';
export const UNPUBLISH_ARTICLE_END = 'UNPUBLISH_ARTICLE_END';
export const UNPUBLISH_ARTICLE_SUCCESS = 'UNPUBLISH_ARTICLE_SUCCESS';
export const UNPUBLISH_ARTICLE_FAILURE = 'UNPUBLISH_ARTICLE_FAILURE';

export const PUBLISH_ARTICLE_START = 'PUBLISH_ARTICLE_START';
export const PUBLISH_ARTICLE_END = 'PUBLISH_ARTICLE_END';
export const PUBLISH_ARTICLE_SUCCESS = 'PUBLISH_ARTICLE_SUCCESS';
export const PUBLISH_ARTICLE_FAILURE = 'PUBLISH_ARTICLE_FAILURE';

export const FETCH_MY_PUBLISHED_ARTICLES_START = 'FETCH_MY_ARTICLES_START';
export const FETCH_MY_PUBLISHED_ARTICLES_END = 'FETCH_MY_ARTICLES_END';
export const FETCH_MY_PUBLISHED_ARTICLES_SUCCESS = 'FETCH_MY_ARTICLES_SUCCESS';
export const FETCH_MY_PUBLISHED_ARTICLES_FAILURE = 'FETCH_MY_ARTICLES_FAILURE';

export const HIGHLIGHT_ARTICLE_START = 'HIGHLIGHT_ARTICLE_START';
export const HIGHLIGHT_ARTICLE_END = 'HIGHLIGHT_ARTICLE_END';
export const HIGHLIGHT_ARTICLE_SUCCESS = 'HIGHLIGHT_ARTICLE_SUCCESS';
export const HIGHLIGHT_ARTICLE_FAILURE = 'HIGHLIGHT_ARTICLE_FAILURE';
export const CLEAR_HIGHLIGHT_ARTICLE_STORE = 'CLEAR_HIGHLIGHT_ARTICLE_STORE';

export const GET_ARTICLE_HIGHLIGHTS_START = 'GET_ARTICLE_HIGHLIGHTS_START';
export const GET_ARTICLE_HIGHLIGHTS_END = 'GET_ARTICLE_HIGHLIGHTS_END';
export const GET_ARTICLE_HIGHLIGHTS_SUCCESS = 'GET_ARTICLE_HIGHLIGHTS_SUCCESS';
export const GET_ARTICLE_HIGHLIGHTS_FAILURE = 'GET_ARTICLE_HIGHLIGHTS_FAILURE';
export const CLEAR_GET_ARTICLE_HIGHLIGHTS_STORE = 'CLEAR_GET_ARTICLE_HIGHLIGHTS_STORE';

export const DELETE_ARTICLE_HIGHLIGHT_START = 'DELETE_ARTICLE_HIGHLIGHT_START';
export const DELETE_ARTICLE_HIGHLIGHT_END = 'DELETE_ARTICLE_HIGHLIGHT_END';
export const DELETE_ARTICLE_HIGHLIGHT_SUCCESS = 'DELETE_ARTICLE_HIGHLIGHT_SUCCESS';
export const DELETE_ARTICLE_HIGHLIGHT_FAILURE = 'DELETE_ARTICLE_HIGHLIGHT_FAILURE';
export const CLEAR_DELETE_ARTICLE_HIGHLIGHT_STORE = 'CLEAR_DELETE_ARTICLE_HIGHLIGHT_STORE';

<<<<<<< HEAD
export const LIKE_ARTICLE_START = 'LIKE_ARTICLE_START';
export const LIKE_ARTICLE_FAILURE = 'LIKE_ARTICLE_FAILURE';
export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_SUCCESS';
export const LIKE_ARTICLE_END = 'LIKE_ARTICLE_END';

export const DISLIKE_ARTICLE_START = 'DISLIKE_ARTICLE_START';
export const DISLIKE_ARTICLE_FAILURE = 'DISLIKE_ARTICLE_FAILURE';
export const DISLIKE_ARTICLE_SUCCESS = 'DISLIKE_ARTICLE_SUCCESS';
export const DISLIKE_ARTICLE_END = 'DISLIKE _ARTICLE_END';

export const GET_ARTICLE_LIKES_START = 'GET_ARTICLE_LIKES_START';
export const GET_ARTICLE_LIKES_FAILURE = 'GET_ARTICLE_LIKES_FAILURE';
export const GET_ARTICLE_LIKES_SUCCESS = 'GET_ARTICLE_LIKES_SUCCESS';
export const GET_ARTICLE_LIKES_END = 'GET_ARTICLE_LIKES_END';
=======
export const BOOKMARK_ARTICLE_START = 'BOOKMARK_ARTICLE_START';
export const BOOKMARK_ARTICLE_END = 'BOOKMARK_ARTICLE_END';
export const BOOKMARK_ARTICLE_SUCCESS = 'BOOKMARK_ARTICLE_SUCCESS';
export const BOOKMARK_ARTICLE_FAILURE = 'BOOKMARK_ARTICLE_FAILURE';
>>>>>>> bookmark article for reading later
