export const DELETE_BOOKMARK_START = 'DELETE_BOOKMARK_START';
export const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS';
export const DELETE_BOOKMARK_FAILURE = 'DELETE_BOOKMARK_FAILURE';
export const DELETE_BOOKMARK_END = 'DELETE_BOOKMARK_END';

export const GET_BOOKMARKS_START = 'GET_BOOKMARKS_START';
export const GET_BOOKMARKS_SUCCESS = 'GET_BOOKMARKS_SUCCESS';
export const GET_BOOKMARKS_FAILURE = 'GET_BOOKMARKS_FAILURE';
export const GET_BOOKMARKS_END = 'GET_BOOKMARKS_END';

export const BOOKMARK_ARTICLE_START = 'BOOKMARK_ARTICLE_START';
export const BOOKMARK_ARTICLE_END = 'BOOKMARK_ARTICLE_END';
export const BOOKMARK_ARTICLE_SUCCESS = 'BOOKMARK_ARTICLE_SUCCESS';
export const BOOKMARK_ARTICLE_FAILURE = 'BOOKMARK_ARTICLE_FAILURE';
