export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const FETCH_COMMENTS_END = 'FETCH_COMMENTS_END';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE';

export const CREATE_COMMENT_START = 'CREATE_COMMENT_START';
export const CREATE_COMMENT_END = 'CREATE_COMMENT_END';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

export const DELETE_COMMENT_START = 'DELETE_COMMENT_START';
export const DELETE_COMMENT_END = 'DELETE_COMMENT_END';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

export const EDIT_COMMENT_START = 'EDIT_COMMENT_START';
export const EDIT_COMMENT_END = 'EDIT_COMMENT_END';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_FAILURE = 'EDIT_COMMENT_FAILURE';

export const FETCH_COMMENT_EDIT_HISTORY_START = 'FETCH_COMMENT_EDIT_HISTORY_START';
export const FETCH_COMMENT_EDIT_HISTORY_END = 'FETCH_COMMENT_EDIT_HISTORY_END';
export const FETCH_COMMENT_EDIT_HISTORY_SUCCESS = 'FETCH_COMMENT_EDIT_HISTORY_SUCCESS';
export const FETCH_COMMENT_EDIT_HISTORY_FAILURE = 'FETCH_COMMENT_EDIT_HISTORY_FAILURE';
