export const GET_FOLLOWERS_START = 'GET_FOLLOWERS_START';
export const GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS';
export const GET_FOLLOWERS_FAILURE = 'GET_FOLLOWERS_FAILURE';
export const GET_FOLLOWERS_END = 'GET_FOLLOWERS_END';

export const GET_FOLLOWING_START = 'GET_FOLLOWING_START';
export const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS';
export const GET_FOLLOWING_FAILURE = 'GET_FOLLOWING_FAILURE';
export const GET_FOLLOWING_END = 'GET_FOLLOWING_END';

export const FOLLOW_AUTHOR_START = 'FOLLOW_AUTHOR_START';
export const FOLLOW_AUTHOR_END = 'FOLLOW_AUTHOR_END';
export const FOLLOW_AUTHOR_SUCCESS = 'FOLLOW_AUTHOR_SUCCESS';
export const FOLLOW_AUTHOR_FAILURE = 'FOLLOW_AUTHOR_FAILURE';

export const UNFOLLOW_AUTHOR_START = 'UNFOLLOW_AUTHOR_START';
export const UNFOLLOW_AUTHOR_END = 'UNFOLLOW_AUTHOR_END';
export const UNFOLLOW_AUTHOR_SUCCESS = 'UNFOLLOW_AUTHOR_SUCCESS';
export const UNFOLLOW_AUTHOR_FAILURE = 'UNFOLLOW_AUTHOR_FAILURE';

export const CLEAR_FOLLOW_STORE = 'CLEAR_FOLLOW_STORE';
