export const LIKE_ARTICLE_START = 'LIKE_ARTICLE_START';
export const LIKE_ARTICLE_FAILURE = 'LIKE_ARTICLE_FAILURE';
export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_SUCCESS';
export const LIKE_ARTICLE_END = 'LIKE_ARTICLE_END';

export const DISLIKE_ARTICLE_START = 'DISLIKE_ARTICLE_START';
export const DISLIKE_ARTICLE_FAILURE = 'DISLIKE_ARTICLE_FAILURE';
export const DISLIKE_ARTICLE_SUCCESS = 'DISLIKE_ARTICLE_SUCCESS';
export const DISLIKE_ARTICLE_END = 'DISLIKE _ARTICLE_END';

export const GET_ARTICLE_LIKES_START = 'GET_ARTICLE_LIKES_START';
export const GET_ARTICLE_LIKES_FAILURE = 'GET_ARTICLE_LIKES_FAILURE';
export const GET_ARTICLE_LIKES_SUCCESS = 'GET_ARTICLE_LIKES_SUCCESS';
export const GET_ARTICLE_LIKES_END = 'GET_ARTICLE_LIKES_END';
