export const LIKE_COMMENT_START = 'LIKE_COMMENT_START';
export const LIKE_COMMENT_FAILURE = 'LIKE_COMMENT_FAILURE';
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS';
export const LIKE_COMMENT_END = 'LIKE_COMMENT_END';

export const GET_COMMENT_LIKES_START = 'GET_COMMENT_LIKES_START';
export const GET_COMMENT_LIKES_FAILURE = 'GET_COMMENT_LIKES_FAILURE';
export const GET_COMMENT_LIKES_SUCCESS = 'GET_COMMENT_LIKES_SUCCESS';
export const GET_COMMENT_LIKES_END = 'GET_COMMENT_LIKES_END';
