export const CREATE_NOTIFICATION_CONFIGURATION_START = 'CREATE_NOTIFICATION_CONFIGURATION_START';
export const CREATE_NOTIFICATION_NOTIFICATION_CONFIGURATION_SUCCESS = 'CREATE_NOTIFICATION_CONFIGURATION_SUCCESS';
export const CREATE_NOTIFICATION_CONFIGURATION_FAILURE = 'CREATE_NOTIFICATION_CONFIGURATION_FAILURE';
export const CREATE_NOTIFICATION_CONFIGURATION_END = 'CREATE_NOTIFICATION_CONFIGURATION_END';

export const GET_NOTIFICATION_CONFIGURATION_START = 'GET_NOTIFICATION_CONFIGURATION_START';
export const GET_NOTIFICATION_CONFIGURATION_SUCCESS = 'GET_NOTIFICATION_CONFIGURATION_SUCCESS';
export const GET_NOTIFICATION_CONFIGURATION_FAILURE = 'GET_NOTIFICATION_CONFIGURATION_FAILURE';
export const GET_NOTIFICATION_CONFIGURATION_END = 'GET_NOTIFICATION_CONFIGURATION_END';

export const UPDATE_NOTIFICATION_CONFIGURATION_START = 'UPDATE_NOTIFICATION_CONFIGURATION_START';
export const UPDATE_NOTIFICATION_CONFIGURATION_END = 'UPDATE_NOTIFICATION_CONFIGURATION_END';
export const UPDATE_NOTIFICATION_CONFIGURATION_SUCCESS = 'UPDATE_NOTIFICATION_CONFIGURATION_SUCCESS';
export const UPDATE_NOTIFICATION_CONFIGURATION_FAILURE = 'UPDATE_NOTIFICATION_CONFIGURATION_FAILURE';

export const TOGGLE_NOTIFICATION_CONFIGURATION_TYPE = 'TOGGLE_NOTIFICATION_CONFIGURATION_TYPE';
export const ADD_OPTION = 'ADD_OPTION';
export const REMOVE_OPTION = 'REMOVE_OPTION';
