export const CREATE_RATING_START = 'CREATE_RATING_START';
export const CREATE_RATING_END = 'CREATE_RATING_END';
export const CREATE_RATING_SUCCESS = 'CREATE_RATING_SUCCESS';
export const CREATE_RATING_FAILURE = 'CREATE_RATING_FAILURE';
export const CLEAR_CREATE_RATING_STORE = 'CLEAR_CREATE_RATING_STORE';
