export const SAVE_READING_STATS_START = 'SAVE_READING_STATS_START';
export const SAVE_READING_STATS_END = 'SAVE_READING_STATS_END';
export const SAVE_READING_STATS_SUCESS = 'SAVE_READING_STATS_SUCESS';
export const SAVE_READING_STATS_FAILURE = 'SAVE_READING_STATS_FAILURE';

export const GET_READING_STATS_START = 'GET_READING_STATS_START';
export const GET_READING_STATS_END = 'GET_READING_STATS_END';
export const GET_READING_STATS_SUCESS = 'GET_READING_STATS_SUCCESS';
export const GET_READING_STATS_FAILURE = 'GET_READING_STATS_FAILURE';
