export const SEARCH_ARTICLE_START = 'SEARCH_ARTICLE_START';
export const SEARCH_ARTICLE_FAILURE = 'SEARCH_ARTICLE_FAILURE';
export const SEARCH_ARTICLE_SUCCESS = 'SEARCH_ARTICLE_SUCCESS';
export const SEARCH_ARTICLE_END = 'SEARCH_ARTICLE_END';
