export const CLEAR_USER_STORE = 'CLEAR_USER_STORE';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_END = 'GET_USER_END';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const SOCIAL_AUTH_START = 'SOCIAL_AUTH_START';
export const SOCIAL_AUTH_END = 'SOCIAL_AUTH_END';
export const SOCIAL_AUTH_SUCCESS = 'SOCIAL_AUTH_SUCCESS';
export const SOCIAL_AUTH_FAILURE = 'SOCIAL_AUTH_FAILURE';

export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_END = 'SIGNUP_USER_END';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_END = 'LOGIN_USER_END';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const EDIT_PROFILE_START = 'EDIT_PROFILE_START';
export const EDIT_PROFILE_END = 'EDIT_PROFILE_END';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

export const UPLOAD_PROFILE_PICTURE_START = 'UPLOAD_PROFILE_PICTURE_START';
export const UPLOAD_PROFILE_PICTURE_END = 'UPLOAD_PROFILE_PICTURE_END';
export const UPLOAD_PROFILE_PICTURE_SUCCESS = 'UPLOAD_PROFILE_PICTURE_SUCCESS';
export const UPLOAD_PROFILE_PICTURE_FAILURE = 'UPLOAD_PROFILE_PICTURE_FAILURE';

export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD_END = 'FORGOT_PASSWORD_END';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_END = 'RESET_PASSWORD_END';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const LOGOUT_USER_START = 'LOGOUT_USER_START';
export const LOGOUT_USER_END = 'LOGOUT_USER_END';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

export const ADMIN_CREATE_USER_START = 'ADMIN_CREATE_USER_START';
export const ADMIN_CREATE_USER_END = 'ADMIN_CREATE_USER_END';
export const ADMIN_CREATE_USER_SUCCESS = 'ADMIN_CREATE_USER_SUCCESS';
export const ADMIN_CREATE_USER_FAILURE = 'ADMIN_CREATE_USER_FAILURE';

export const ADMIN_GET_USERS_START = 'ADMIN_GET_USERS_START';
export const ADMIN_GET_USERS_END = 'ADMIN_GET_USERS_END';
export const ADMIN_GET_USERS_SUCCESS = 'ADMIN_GET_USERS_SUCCESS';
export const ADMIN_GET_USERS_FAILURE = 'ADMIN_GET_USERS_FAILURE';

export const ADMIN_GET_PERMISSIONS_START = 'ADMIN_GET_PERMISSIONS_START';
export const ADMIN_GET_PERMISSIONS_END = 'ADMIN_GET_PERMISSIONS_END';
export const ADMIN_GET_PERMISSIONS_SUCCESS = 'ADMIN_GET_PERMISSIONS_SUCCESS';
export const ADMIN_GET_PERMISSIONS_FAILURE = 'ADMIN_GET_PERMISSIONS_FAILURE';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_END = 'DELETE_USER_END';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const SEARCH_USER_START = 'SEARCH_USER_START';
export const SEARCH_USER_END = 'SEARCH_USER_END';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAILURE = 'SEARCH_USER_FAILURE';

export const ADMIN_EDIT_PROFILE_START = 'ADMIN_EDIT_PROFILE_START';
export const ADMIN_EDIT_PROFILE_END = 'ADMIN_EDIT_PROFILE_END';
export const ADMIN_EDIT_PROFILE_SUCCESS = 'ADMIN_EDIT_PROFILE_SUCCESS';
export const ADMIN_EDIT_PROFILE_FAILURE = 'ADMIN_EDIT_PROFILE_FAILURE';
